/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2019-03-02 05:25:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.school.admin.category.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import book_table.Admin_Book_Table_Model;
import common_use_bean.Book_Use_Bean;
import category_table.Category_Table;
import common_use_bean.Category_Use_Bean;
import java.util.List;
import common_use_bean.Admin_Use_Bean;
import common.Common_Things;
import java.util.Iterator;
import java.util.TimeZone;
import java.text.SimpleDateFormat;
import java.util.Date;

public final class Edit_005fCategory_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/school/admin/category/view/../../common/tab.jsp", Long.valueOf(1551503612314L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html class=\"no-js\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <!-- meta -->\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    \n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- bootstrap -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/bootstrap/css/bootstrap.min.css\">\n");
      out.write("    <!-- /bootstrap -->\n");
      out.write("\n");
      out.write("    <!-- core styles -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/main.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/animate.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/vendor/offline/theme.css\">\n");
      out.write("    <!-- /core styles -->\n");
      out.write("\n");
      out.write("    <!-- page styles -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/vendor/toastr/toastr.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/vendor/jvectormap/jquery-jvectormap-1.2.2.css\">\n");
      out.write("    <!-- /page styles -->\n");
      out.write("\n");
      out.write("    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("\n");
      out.write("    <!-- load modernizer -->\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/vendor/modernizr.js\"></script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<!-- body -->\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\t\n");
      out.write("    <div class=\"app\" data-sidebar=\"locked\">\n");
      out.write("        <!-- top header -->\n");
      out.write("        \n");
      out.write("               ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");

	List<Admin_Use_Bean> list1=(List<Admin_Use_Bean>)session.getAttribute("ss_ADMIN_bean");
	Admin_Use_Bean obj_Admin_Use_Bean=new Admin_Use_Bean();
	if(list1==null){
		
		
		
		session.setAttribute("ss_school_index_message","Opps..Your session expired,Please Login Again");
	
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\twindow.location.href=\"");
      out.print(Common_Things.url );
      out.write("\";\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t");

	}else{
	
	Iterator<Admin_Use_Bean> it_list=list1.iterator();
	obj_Admin_Use_Bean=it_list.next();
	
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Library Management | ColourChalk</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<header class=\"header header-fixed navbar bg-white\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"brand bg-success\">\r\n");
      out.write("                <a href=\"#\" class=\"fa fa-bars off-left visible-xs\" data-toggle=\"off-canvas\" data-move=\"ltr\"></a>\r\n");
      out.write("\r\n");
      out.write("                 <a href=\"");
      out.print(Common_Things.url );
      out.write("/admin-home\" class=\"navbar-brand text-white\">\r\n");
      out.write("                    <i class=\"fa fa-user mg-r-xs\"></i> \r\n");
      out.write("                    <span>\r\n");
      out.write("                        <b>LIBRARY</b> CC\r\n");
      out.write("                    </span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t\t\t<div class=\"collapse navbar-collapse pull-left no-padding\" id=\"hor-menu\">\r\n");
      out.write("                <ul class=\"nav navbar-nav\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");

					TimeZone.setDefault(TimeZone.getTimeZone("Asia/Qatar")); 
					SimpleDateFormat format = new SimpleDateFormat("dd-MMM-yyyy hh:mm a");
					 
					  Date today4 = new Date();
						
						
				       String date4 = format.format(today4);
					
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <span>");
      out.print(date4 );
      out.write("</span>\r\n");
      out.write("                           \r\n");
      out.write("                        </a>\r\n");
      out.write("                      \r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                   \r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right off-right\">\r\n");
      out.write("                <li class=\"hidden-xs\">\r\n");
      out.write("                    <a href=\"");
      out.print(Common_Things.url );
      out.write("/edit-profile-admin/\">\r\n");
      out.write("                        +ADMIN\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li> \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                 \r\n");
      out.write("                <li class=\"quickmenu mg-r-md\">\r\n");
      out.write("                    <a href=\"");
      out.print(Common_Things.url );
      out.write("/Admin_Sign_Out_Controller\">\r\n");
      out.write("                        <i>Logout</i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                   \r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </header>\r\n");
      out.write("        <!-- /top header -->\r\n");
      out.write("\r\n");
      out.write("        <section class=\"layout\">\r\n");
      out.write("            <!-- sidebar menu -->\r\n");
      out.write("            <aside class=\"sidebar canvas-left bg-dark\">\r\n");
      out.write("                <!-- main navigation -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t <nav class=\"main-navigation\">\r\n");
      out.write("\t\t\t\t\t\t\t\t                    <ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t                        <li>\r\n");
      out.write("\t\t\t\t\t\t\t\t                            <a href=\"");
      out.print(Common_Things.url );
      out.write("/search-book/\">\r\n");
      out.write("\t\t\t\t\t\t\t\t                                <i class=\"fa fa-book\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t                                <span>Book</span> \r\n");
      out.write("\t\t\t\t\t\t\t\t                            </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t                            \r\n");
      out.write("\t\t\t\t\t\t\t\t                                              \r\n");
      out.write("\t\t\t\t\t\t\t\t                             \r\n");
      out.write("\t\t\t\t\t\t\t\t                                        \r\n");
      out.write("\t\t\t\t\t\t\t\t                        </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t                       \r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t <li>\r\n");
      out.write("\t\t\t\t\t\t\t\t                            <a href=\"");
      out.print(Common_Things.url );
      out.write("/admin-add-category\">\r\n");
      out.write("\t\t\t\t\t\t\t\t                                <i class=\"fa fa-edit\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t                                <span>Category</span> \r\n");
      out.write("\t\t\t\t\t\t\t\t                            </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t                            \r\n");
      out.write("\t\t\t\t\t\t\t\t                             \r\n");
      out.write("\t\t\t\t\t\t\t\t                             \r\n");
      out.write("\t\t\t\t\t\t\t\t                            \r\n");
      out.write("\t\t\t\t\t\t\t\t                        </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t                       \r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t                     \t <li>\r\n");
      out.write("\t\t\t\t\t\t\t\t                            <a href=\"");
      out.print(Common_Things.url );
      out.write("/add-author\">\r\n");
      out.write("\t\t\t\t\t\t\t\t                                <i class=\"fa fa-coffee\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t                                <span>Author</span>  \r\n");
      out.write("\t\t\t\t\t\t\t\t                            </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t                        </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t                       \t <li>\r\n");
      out.write("\t\t\t\t\t\t\t\t                            <a href=\"");
      out.print(Common_Things.url );
      out.write("/student-search/\">\r\n");
      out.write("\t\t\t\t\t\t\t\t                                <i class=\"fa fa-users\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t                                <span>Student</span>  \r\n");
      out.write("\t\t\t\t\t\t\t\t                            </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t                        </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t                       \r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t                       \t <li>\r\n");
      out.write("\t\t\t\t\t\t\t\t                            <a href=\"");
      out.print(Common_Things.url );
      out.write("/complete-issue-history/\">\r\n");
      out.write("\t\t\t\t\t\t\t\t                                <i class=\"fa fa-legal\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t                                <span>Issue History</span>  \r\n");
      out.write("\t\t\t\t\t\t\t\t                            </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t                        </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t                       \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t                        \r\n");
      out.write("\t\t\t\t\t\t\t\t                        \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");

														/*
														<li>
								                            <a href="">
								                                <i class="fa fa-calendar"></i>
								                                <span>Calendar</span>
								                            </a>
								                        </li>

														<li>
								                            <a href="">
								                                <i class="fa fa-tags"></i>
								                                <span>Task</span>
								                            </a>
								                        </li>
														*/
														
														
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t                    </ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t                </nav>\r\n");
      out.write("\t <!-- /main navigation -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("              \r\n");
      out.write("\t </aside>\r\n");
      out.write("            <!-- /sidebar menu -->\r\n");
      out.write("\t\r\n");
      out.write("\t");

	}
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("               \n");
      out.write("           \n");
      out.write("\n");
      out.write("           \n");
      out.write("\n");
      out.write("            <!-- main content -->\n");
      out.write("            <section class=\"main-content\">\n");
      out.write("\n");
      out.write("                <!-- content wrapper -->\n");
      out.write("                <div class=\"content-wrap\">\n");
      out.write("\n");
      out.write("                    <div class=\"row mg-b\">\n");
      out.write("                        <div class=\"col-xs-6\"> \n");
      out.write("                            <h3 class=\"no-margin\">Add Category</h3>\n");
      out.write("                            \n");
      out.write("                        </div>\n");
      out.write("                       \n");
      out.write("                    </div>             \n");
      out.write("\n");
      out.write("                    <div class=\"col-lg-6\">\n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                    \t\t");

							String message=(String)session.getAttribute("add_category_message");
							if(message!=null){
							
      out.write(" \n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t <div class=\"alert alert-success\">\n");
      out.write("                                        ");
      out.print(message);
      out.write("\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t");
			session.removeAttribute("add_category_message");
							}
							
      out.write("\n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                    \t\t");

                    		String sl_no=(String)request.getParameter("sl_no");
                    		String category_name=(String)request.getParameter("n");
                    		String desc=(String)request.getParameter("d");
                    		
                    		
      out.write("\n");
      out.write("                    \t\t\n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                                            <section class=\"panel\">\n");
      out.write("                                                <header class=\"panel-heading\">Edit Category</header>\n");
      out.write("                                                <div class=\"panel-body\">\n");
      out.write("\n");
      out.write("                                                    <form action=\"");
      out.print(Common_Things.url);
      out.write("/edit-category-contro/\" class=\"form-horizontal\" role=\"form\">\n");
      out.write("                                                       \n");
      out.write("                                                       <input type=\"hidden\" name=\"sl_no\" value=\"");
      out.print(sl_no );
      out.write("\">\n");
      out.write("                                                        <div class=\"form-group\">\n");
      out.write("                                                            <label for=\"inputEmail3\" class=\"col-sm-2 control-label\">Category </label>\n");
      out.write("                                                            \t<div class=\"col-sm-10\">\n");
      out.write("                                                               \t<input type=\"text\" class=\"form-control\" value=\"");
      out.print(category_name );
      out.write("\" name=\"category_name\" data-parsley-required=\"true\" data-parsley-trigger=\"change\" placeholder=\"Category \">\n");
      out.write("                                                               </div> \n");
      out.write("                                                             \n");
      out.write("                                                        </div> \n");
      out.write("                                                        \n");
      out.write("                                                       <div class=\"form-group\">\n");
      out.write("                                                            <label for=\"inputEmail3\" class=\"col-sm-2 control-label\">Description</label>\n");
      out.write("                                                            <div class=\"col-sm-10\"> \n");
      out.write("                                                            \n");
      out.write("                                                            \t<textarea rows=\"5\" class=\"form-control\" placeholder=\"Description\" name=\"profile\">");
if(!desc.equals("null")){out.println(desc);} 
      out.write("</textarea>\n");
      out.write("                                                               \n");
      out.write("                                                            </div> \n");
      out.write("                                                        </div>\n");
      out.write("                                                        \n");
      out.write("                                                     \n");
      out.write("                                                     <hr> \n");
      out.write("                                                     \n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"form-group\">  \n");
      out.write("                                                            <div class=\"col-sm-offset-2 col-sm-15\">\n");
      out.write("                                                                <button type=\"submit\" class=\"btn btn-default\">Update</button>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </form>\n");
      out.write("\n");
      out.write("                                                </div> \n");
      out.write("                                                \n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("                    <div class=\"col-lg-6\">\n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                        \n");
      out.write("                    \n");
      out.write("                                            <section class=\"panel\">\n");
      out.write("                                                <header class=\"panel-heading\">Search Category</header>\n");
      out.write("                                                <div class=\"panel-body\">\n");
      out.write("\n");
      out.write("                                                    <form action=\"");
      out.print(Common_Things.url);
      out.write("/admin-search-category/\" class=\"form-horizontal\" role=\"form\">\n");
      out.write("                                                        <div class=\"form-group\">\n");
      out.write("                                                            <label for=\"inputEmail3\" class=\"col-sm-2 control-label\">Category </label>\n");
      out.write("                                                            \t<div class=\"col-sm-10\">\n");
      out.write("                                                               \t<input type=\"text\" class=\"form-control\" name=\"search\" data-parsley-required=\"true\" data-parsley-trigger=\"change\" placeholder=\"Category Search\">\n");
      out.write("                                                               </div> \n");
      out.write("                                                             \n");
      out.write("                                                        </div> \n");
      out.write("                                                        \n");
      out.write("                                                       \n");
      out.write("                                                         \n");
      out.write("                                                     \n");
      out.write("                                                     <hr> \n");
      out.write("                                                     \n");
      out.write("                                                         \n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"form-group\">   \n");
      out.write("                                                            <div class=\"col-sm-offset-2 col-sm-15\">\n");
      out.write("                                                                <button type=\"submit\" class=\"btn btn-default\">Search</button>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </form>\n");
      out.write("\n");
      out.write("                                                </div> \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\n");
      out.write("\n");
      out.write("\n");
      out.write("                             \n");
      out.write("\n");
      out.write("\n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("                <!-- /content wrapper -->\n");
      out.write("            </section>\n");
      out.write("            <!-- /main content -->\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div data-phase=\"1\" class=\"offline-ui\">\n");
      out.write("        <div class=\"offline-ui-content\" data-retry-in=\"\" data-retry-in-abbr=\"\"></div>\n");
      out.write("        <a class=\"offline-ui-retry\"></a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- core scripts -->\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/jquery-1.11.0.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/bootstrap/js/bootstrap.js\"></script>\n");
      out.write("    <!-- /core scripts -->\n");
      out.write("\n");
      out.write("    <!-- page scripts -->\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/toastr/toastr.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/moment.js\"></script>\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/skycons.js\"></script>\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/jquery.blockUI.js\"></script>\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/raphael.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/morris/morris.js\"></script>\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/switchery/switchery.js\"></script>\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/jquery.slimscroll.js\"></script>\n");
      out.write("    <!-- /page scripts -->\n");
      out.write("\n");
      out.write("    <!-- theme scripts -->\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/off-canvas.js\"></script>\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/offline/offline.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/main.js\"></script>\n");
      out.write("    <!-- /theme scripts -->\n");
      out.write("\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/dashboard.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("<!-- /body -->\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
