/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2019-03-02 05:25:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.school.admin.profile.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import student_table.Student_Table_Model;
import common_use_bean.Student_Use_Bean;
import admin_table.Admin_Profile_Model;
import java.util.List;
import common_use_bean.Admin_Use_Bean;
import common.Common_Things;
import java.util.Iterator;
import java.util.TimeZone;
import java.text.SimpleDateFormat;
import java.util.Date;

public final class Edit_005fProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/school/admin/profile/view/../../common/tab.jsp", Long.valueOf(1551503612314L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html class=\"no-js\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <!-- meta -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- bootstrap -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- /bootstrap -->\r\n");
      out.write("\r\n");
      out.write("    <!-- core styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/main.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/animate.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/vendor/offline/theme.css\">\r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/vendor/bootstrap-datepicker/datepicker.css\">\r\n");
      out.write("    <!-- /core styles -->\r\n");
      out.write("\r\n");
      out.write("    <!-- page styles -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- /page styles -->\r\n");
      out.write("\r\n");
      out.write("    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("    <!-- load modernizer -->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/vendor/modernizr.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!-- body -->\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("    <div class=\"app\" data-sidebar=\"locked\">\r\n");
      out.write("        <!-- top header -->\r\n");
      out.write("        \r\n");
      out.write("               ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");

	List<Admin_Use_Bean> list1=(List<Admin_Use_Bean>)session.getAttribute("ss_ADMIN_bean");
	Admin_Use_Bean obj_Admin_Use_Bean=new Admin_Use_Bean();
	if(list1==null){
		
		
		
		session.setAttribute("ss_school_index_message","Opps..Your session expired,Please Login Again");
	
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\twindow.location.href=\"");
      out.print(Common_Things.url );
      out.write("\";\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t");

	}else{
	
	Iterator<Admin_Use_Bean> it_list=list1.iterator();
	obj_Admin_Use_Bean=it_list.next();
	
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Library Management | ColourChalk</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<header class=\"header header-fixed navbar bg-white\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"brand bg-success\">\r\n");
      out.write("                <a href=\"#\" class=\"fa fa-bars off-left visible-xs\" data-toggle=\"off-canvas\" data-move=\"ltr\"></a>\r\n");
      out.write("\r\n");
      out.write("                 <a href=\"");
      out.print(Common_Things.url );
      out.write("/admin-home\" class=\"navbar-brand text-white\">\r\n");
      out.write("                    <i class=\"fa fa-user mg-r-xs\"></i> \r\n");
      out.write("                    <span>\r\n");
      out.write("                        <b>LIBRARY</b> CC\r\n");
      out.write("                    </span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t\t\t<div class=\"collapse navbar-collapse pull-left no-padding\" id=\"hor-menu\">\r\n");
      out.write("                <ul class=\"nav navbar-nav\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");

					TimeZone.setDefault(TimeZone.getTimeZone("Asia/Qatar")); 
					SimpleDateFormat format = new SimpleDateFormat("dd-MMM-yyyy hh:mm a");
					 
					  Date today4 = new Date();
						
						
				       String date4 = format.format(today4);
					
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <span>");
      out.print(date4 );
      out.write("</span>\r\n");
      out.write("                           \r\n");
      out.write("                        </a>\r\n");
      out.write("                      \r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                   \r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right off-right\">\r\n");
      out.write("                <li class=\"hidden-xs\">\r\n");
      out.write("                    <a href=\"");
      out.print(Common_Things.url );
      out.write("/edit-profile-admin/\">\r\n");
      out.write("                        +ADMIN\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li> \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                 \r\n");
      out.write("                <li class=\"quickmenu mg-r-md\">\r\n");
      out.write("                    <a href=\"");
      out.print(Common_Things.url );
      out.write("/Admin_Sign_Out_Controller\">\r\n");
      out.write("                        <i>Logout</i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                   \r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </header>\r\n");
      out.write("        <!-- /top header -->\r\n");
      out.write("\r\n");
      out.write("        <section class=\"layout\">\r\n");
      out.write("            <!-- sidebar menu -->\r\n");
      out.write("            <aside class=\"sidebar canvas-left bg-dark\">\r\n");
      out.write("                <!-- main navigation -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t <nav class=\"main-navigation\">\r\n");
      out.write("\t\t\t\t\t\t\t\t                    <ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t                        <li>\r\n");
      out.write("\t\t\t\t\t\t\t\t                            <a href=\"");
      out.print(Common_Things.url );
      out.write("/search-book/\">\r\n");
      out.write("\t\t\t\t\t\t\t\t                                <i class=\"fa fa-book\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t                                <span>Book</span> \r\n");
      out.write("\t\t\t\t\t\t\t\t                            </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t                            \r\n");
      out.write("\t\t\t\t\t\t\t\t                                              \r\n");
      out.write("\t\t\t\t\t\t\t\t                             \r\n");
      out.write("\t\t\t\t\t\t\t\t                                        \r\n");
      out.write("\t\t\t\t\t\t\t\t                        </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t                       \r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t <li>\r\n");
      out.write("\t\t\t\t\t\t\t\t                            <a href=\"");
      out.print(Common_Things.url );
      out.write("/admin-add-category\">\r\n");
      out.write("\t\t\t\t\t\t\t\t                                <i class=\"fa fa-edit\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t                                <span>Category</span> \r\n");
      out.write("\t\t\t\t\t\t\t\t                            </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t                            \r\n");
      out.write("\t\t\t\t\t\t\t\t                             \r\n");
      out.write("\t\t\t\t\t\t\t\t                             \r\n");
      out.write("\t\t\t\t\t\t\t\t                            \r\n");
      out.write("\t\t\t\t\t\t\t\t                        </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t                       \r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t                     \t <li>\r\n");
      out.write("\t\t\t\t\t\t\t\t                            <a href=\"");
      out.print(Common_Things.url );
      out.write("/add-author\">\r\n");
      out.write("\t\t\t\t\t\t\t\t                                <i class=\"fa fa-coffee\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t                                <span>Author</span>  \r\n");
      out.write("\t\t\t\t\t\t\t\t                            </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t                        </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t                       \t <li>\r\n");
      out.write("\t\t\t\t\t\t\t\t                            <a href=\"");
      out.print(Common_Things.url );
      out.write("/student-search/\">\r\n");
      out.write("\t\t\t\t\t\t\t\t                                <i class=\"fa fa-users\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t                                <span>Student</span>  \r\n");
      out.write("\t\t\t\t\t\t\t\t                            </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t                        </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t                       \r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t                       \t <li>\r\n");
      out.write("\t\t\t\t\t\t\t\t                            <a href=\"");
      out.print(Common_Things.url );
      out.write("/complete-issue-history/\">\r\n");
      out.write("\t\t\t\t\t\t\t\t                                <i class=\"fa fa-legal\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t                                <span>Issue History</span>  \r\n");
      out.write("\t\t\t\t\t\t\t\t                            </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t                        </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t                       \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t                        \r\n");
      out.write("\t\t\t\t\t\t\t\t                        \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");

														/*
														<li>
								                            <a href="">
								                                <i class="fa fa-calendar"></i>
								                                <span>Calendar</span>
								                            </a>
								                        </li>

														<li>
								                            <a href="">
								                                <i class="fa fa-tags"></i>
								                                <span>Task</span>
								                            </a>
								                        </li>
														*/
														
														
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t                    </ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t                </nav>\r\n");
      out.write("\t <!-- /main navigation -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("              \r\n");
      out.write("\t </aside>\r\n");
      out.write("            <!-- /sidebar menu -->\r\n");
      out.write("\t\r\n");
      out.write("\t");

	}
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("               \r\n");
      out.write("           \r\n");
      out.write("\r\n");
      out.write("           \r\n");
      out.write("\r\n");
      out.write("            <!-- main content -->\r\n");
      out.write("            <section class=\"main-content\">\r\n");
      out.write("\r\n");
      out.write("                <!-- content wrapper -->\r\n");
      out.write("                <div class=\"content-wrap\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"row mg-b\">\r\n");
      out.write("                        <div class=\"col-xs-6\"> \r\n");
      out.write("                            <h3 class=\"no-margin\">Edit Admin</h3>\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-lg-8\">\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \t\t");

							String message=(String)session.getAttribute("edit_profle_message");
							if(message!=null){
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t <div class=\"alert alert-success\">\r\n");
      out.write("                                        ");
      out.print(message);
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
			session.removeAttribute("edit_profle_message");
							}
							
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \t");

                    	Admin_Profile_Model obj_Admin_Profile_Model=new Admin_Profile_Model();
                    	obj_Admin_Use_Bean=obj_Admin_Profile_Model.get_admin_details(obj_Admin_Use_Bean);
                    	
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                     \r\n");
      out.write("                    \r\n");
      out.write("                                            <section class=\"panel\"> \r\n");
      out.write("                                                <header class=\"panel-heading\">Edit Admin Details</header>\r\n");
      out.write("                                                <div class=\"panel-body\">\r\n");
      out.write("\r\n");
      out.write("                                                    <form action=\"");
      out.print(Common_Things.url);
      out.write("/edit-profile-controller/\" class=\"form-horizontal\" role=\"form\" method=\"post\">\r\n");
      out.write("                                                        <div class=\"form-group\">\r\n");
      out.write("                                                            <label for=\"inputEmail3\" class=\"col-sm-2 control-label\">User Name</label>\r\n");
      out.write("                                                            \t<div class=\"col-sm-10\">\r\n");
      out.write("                                                               \t<input type=\"text\" class=\"form-control\" name=\"admission_no\" data-parsley-required=\"true\" data-parsley-trigger=\"change\" placeholder=\"User Name\" value=\"");
if(obj_Admin_Use_Bean.getUser_name()!=null){out.println(obj_Admin_Use_Bean.getUser_name());} 
      out.write("\" readonly=\"readonly\">\r\n");
      out.write("                                                               </div> \r\n");
      out.write("                                                             \r\n");
      out.write("                                                        </div> \r\n");
      out.write("                                                        \r\n");
      out.write("                                                       \r\n");
      out.write("                                                        \t<hr>\r\n");
      out.write("                                                           \r\n");
      out.write("                                                        <div class=\"form-group\">\r\n");
      out.write("                                                            <label for=\"inputEmail3\" class=\"col-sm-2 control-label\">New User Name</label>\r\n");
      out.write("                                                            \t<div class=\"col-sm-10\">\r\n");
      out.write("                                                               \t<input type=\"text\" class=\"form-control\" name=\"user_name\" data-parsley-required=\"true\" data-parsley-trigger=\"change\" placeholder=\"User Name\" value=\"");
if(obj_Admin_Use_Bean.getUser_name()!=null){out.println(obj_Admin_Use_Bean.getUser_name());} 
      out.write("\">\r\n");
      out.write("                                                               </div> \r\n");
      out.write("                                                             \r\n");
      out.write("                                                        </div> \r\n");
      out.write("                                                        \r\n");
      out.write("                                                       \r\n");
      out.write("                                                        \t<hr>\r\n");
      out.write("                                                           \r\n");
      out.write("                                                       \r\n");
      out.write("                                                         \r\n");
      out.write("                                                         \r\n");
      out.write("                                                        \r\n");
      out.write("                                                         <div class=\"form-group\">\r\n");
      out.write("                                                            <label for=\"inputEmail3\" class=\"col-sm-2 control-label\">Old Password</label>\r\n");
      out.write("                                                            <div class=\"col-sm-10\">\r\n");
      out.write("                                                                <input type=\"password\" class=\"form-control\" placeholder=\"Password\" name=\"password\">\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        \r\n");
      out.write("                                                        \r\n");
      out.write("                                                       \t\t<hr> \r\n");
      out.write("                                                        \r\n");
      out.write("                                                        \r\n");
      out.write("                                                          <div class=\"form-group\">\r\n");
      out.write("                                                            <label for=\"inputEmail3\" class=\"col-sm-2 control-label\">New Password</label>\r\n");
      out.write("                                                            <div class=\"col-sm-10\">\r\n");
      out.write("                                                                <input type=\"password\" class=\"form-control\" placeholder=\"Password\" name=\"new_password\">\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        \r\n");
      out.write("                                                        \r\n");
      out.write("                                                       \t\t<hr> \r\n");
      out.write("                                                        \r\n");
      out.write("                                                        \r\n");
      out.write("                                                         \r\n");
      out.write("                                                        \r\n");
      out.write("                                                        \r\n");
      out.write("                                                        \r\n");
      out.write("                                                        \r\n");
      out.write("                                                        <div class=\"form-group\">  \r\n");
      out.write("                                                            <div class=\"col-sm-offset-2 col-sm-15\">\r\n");
      out.write("                                                                <button type=\"submit\" class=\"btn btn-default\">Update</button>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        \r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </form>\r\n");
      out.write("\r\n");
      out.write("                                                </div> \r\n");
      out.write("                                                \r\n");
      out.write("                                                  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /content wrapper -->\r\n");
      out.write("            </section>\r\n");
      out.write("            <!-- /main content -->\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- core scripts --> \r\n");
      out.write(" \t\r\n");
      out.write("    <!-- /core scripts -->\r\n");
      out.write("\r\n");
      out.write("    <!-- page scripts -->\r\n");
      out.write("  \t<script src=\"");
      out.print(Common_Things.url );
      out.write("/vendor/bootstrap-select/bootstrap-select.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(Common_Things.url );
      out.write("/vendor/datatables/jquery.dataTables.js\"></script>\r\n");
      out.write("    <!-- /page scripts -->\r\n");
      out.write("\r\n");
      out.write("    <!-- theme scripts -->\r\n");
      out.write("    <script src=\"");
      out.print(Common_Things.url );
      out.write("/vendor/slider/bootstrap-slider.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(Common_Things.url );
      out.write("/js/off-canvas.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(Common_Things.url );
      out.write("/vendor/offline/offline.min.js\"></script>\r\n");
      out.write("     <script src=\"");
      out.print(Common_Things.url );
      out.write("/vendor/bootstrap-datepicker/bootstrap-datepicker.js\"></script>\r\n");
      out.write("       \r\n");
      out.write("     \r\n");
      out.write("        <script src=\"");
      out.print(Common_Things.url );
      out.write("/js/main.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(Common_Things.url );
      out.write("/js/datatables.js\"></script>\r\n");
      out.write("\t <script src=\"");
      out.print(Common_Things.url );
      out.write("/vendor/switchery/switchery.js\"></script>\r\n");
      out.write("     <script src=\"");
      out.print(Common_Things.url );
      out.write("/js/forms.js\"></script>\r\n");
      out.write("      \r\n");
      out.write("\t  \r\n");
      out.write("\r\n");
      out.write("    <!-- /theme scripts -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<!-- /body -->\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
