/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2019-03-09 07:39:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Registration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>RegForm</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
session.getAttribute("session"); 
      out.write('\r');
      out.write('\n');
System.out.println("session id" + session.getId()); 
      out.write("\r\n");
      out.write("\r\n");
 application.getInitParameter("context");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<p>Hello JsP</p>\r\n");
      out.write("<form onsubmit=\"return Validate()\" action=\"Registration\">\r\n");
      out.write("UserId:\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"UserId\" value=");
      out.print(request.getParameter("userId"));
      out.write("><br/>\r\n");
      out.write("\r\n");
      out.write("UserName:\r\n");
      out.write("\t\t\t<input type=\"text\"  id = \"id1\" name=\"name\" /><br/>\r\n");
      out.write("\t\t\t<span id =\"nameerror\"></span>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tGender:\r\n");
      out.write("\t\t\t<input type=\"radio\" name=\"gender\" class= \"g1\" value=\"Male\" /> Male\r\n");
      out.write("\t\t\t<input type=\"radio\" name=\"gender\" class= \"g1\" value=\"Female\"  /> Female&nbsp;<br\\>\r\n");
      out.write("\t\t\t<span class=\"gendererror\"></span>\r\n");
      out.write("\t\t\t<br/>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tPhoneNo:\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"nPhoneNo\" /><br/>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tCities:\r\n");
      out.write("\t\t\t<input type=\"checkbox\" name=\"city\" class=\"c1\"  value=\"Bengaluru\"/> Bengaluru\r\n");
      out.write("\t\t\t<input type=\"checkbox\" name=\"city\" class=\"c1\"  value=\" Chennai\" />Chennai\r\n");
      out.write("\t\t\t<input type=\"checkbox\" name=\"city\" class=\"c1\" value=\"Delhi\"/> Delhi\r\n");
      out.write("\t\t\t<input type=\"checkbox\" name=\"city\"  class=\"c1\" value=\"Kolkata\"/> Kolkata\r\n");
      out.write("\t\t\t<span class=\"cityerror\"></span>\r\n");
      out.write("\t\t\t<br/>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tTechnology:\r\n");
      out.write("\t\t\t<select name=\"Technologies\" class=\"t1\">\r\n");
      out.write("\t\t\t<option value=\"html\" class=\"t1\"  name=\"technologies\" >HTML</option>\r\n");
      out.write("\t\t\t<option value=\"CSS\" class=\"t1\" name=\"technologies\" >CSS</option>\r\n");
      out.write("\t\t\t<option value=\"bootstrap\" class=\"t1\" name=\"technologies\" >Bootstrap</option>\r\n");
      out.write("\t\t\t<option value=\"js\" class=\"t1\" name=\"technologies\" >JS</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<span class=\"techerror\"></span>\r\n");
      out.write("\t\t\t<br/>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<input type = \"submit\"> \r\n");
      out.write("</form>\r\n");
      out.write("<script type=text/javascript>\r\n");
      out.write("function Validate()\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("var flagName = nameValidate(name);\r\n");
      out.write("var flagGender = genderValidate();\r\n");
      out.write("var flagCity = cityValidate();\r\n");
      out.write("var flagtechnology = technologyValidate();\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("if(flagName && flagGender && flagCity && flagtechnology)\r\n");
      out.write("return true;\r\n");
      out.write("else\r\n");
      out.write("return false;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\tfunction nameValidate(name)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar name=document.getElementById(\"id1\").value;\r\n");
      out.write("\t\tif(name.match(\"^[A-Za-z]+$\"))\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\tdocument.getElementById(\"nameerror\").innerHTML=\"Name can have only characters\";\t\r\n");
      out.write("\t\tdocument.getElementById(\"nameerror\").style.color=\"red\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction genderValidate(gender)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar flag = false;\r\n");
      out.write("\t\tvar gender = document.getElementsByClassName(\"g1\");\r\n");
      out.write("\t\tfor(var i = 0; i<gender.length;i++){\r\n");
      out.write("\t\t\tif(gender[i].checked){\r\n");
      out.write("\t\t\t\tflag = true;\r\n");
      out.write("\t\t\t\tconsole.log(flag);\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(!flag){\r\n");
      out.write("\t\t\tdocument.getElementsByClassName(\"gendererror\").innerHTML=\"one of the radio button is not selected\";\r\n");
      out.write("\t\t\t\tdocument.getElementsByClassName(\"gendererror\").style.color=\"red\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn flag;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction cityValidate(city)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar flag = false;\r\n");
      out.write("\t\tvar city=document.getElementsByClassName(\"c1\");\r\n");
      out.write("\t\tfor(var i = 0; i<city.length;i++){\r\n");
      out.write("\t\t\tif(city[i].checked){\r\n");
      out.write("\t\t\t\tflag = true;\r\n");
      out.write("\t\t\t\tconsole.log(flag);\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(!flag){\r\n");
      out.write("\t\t\tdocument.getElementsByClassName(\"cityerror\").innerHTML=\"one of the checkbox is not selected\";\r\n");
      out.write("\t\t\t\tdocument.getElementsByClassName(\"cityerror\").style.color=\"red\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\treturn flag;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction technologyValidate()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar flag = false;\r\n");
      out.write("\t\tvar technology=document.getElementsByClassName(\"t1\");\r\n");
      out.write("\t\tfor(var i = 0; i<technology.length;i++){\r\n");
      out.write("\t\t\tif(technology[i].checked){\r\n");
      out.write("\t\t\t\tflag = true;\r\n");
      out.write("\t\t\t\tconsole.log(flag);\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(!flag){\r\n");
      out.write("\t\t\tdocument.getElementsByClassName(\"techerror\").innerHTML=\"please select an option\";\r\n");
      out.write("\t\t\t\tdocument.getElementsByClassName(\"techerror\").style.color=\"red\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn flag;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
