/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2019-03-08 07:30:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import nsp.HibernateUtil;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
String name1="jjjj";
      out.write('\r');
      out.write('\n');
 HibernateUtil util = new HibernateUtil();
util.createSessionFactory();
      out.write("\r\n");
      out.write("<form method=\"post\"  action=\"LoginServlet\">\r\n");
      out.write("UserName\r\n");
      out.write("<input type=\"text\" name=\"username\" placeholder=\"please enter user name\" id=\"id1\" /><br>\r\n");
      out.write("<span id='error1'></span></br>\r\n");
      out.write("Password\r\n");
      out.write("<input type=\"password\" name=\"password\" id=\"id2\" placeholder=\"please enter user password\" />\r\n");
      out.write("<span id='error2'></span></br>\r\n");
      out.write("<input type=\"submit\"/>\r\n");
      out.write("\r\n");
      out.write("<span id=\"time\"></span>\r\n");
      out.write("</form>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("setInterval(getTime,1000);\r\n");
      out.write("function getTime(){\r\n");
      out.write("\tdocument.getElementById(\"time\").innerHTML=new Date();\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("/*\r\n");
      out.write("\t    function validate(){\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \tvar name=document.getElementById(\"id1\").value;\r\n");
      out.write("\t    \tvar password=document.getElementById(\"id2\").value;\r\n");
      out.write("\t    \tvar patternName=\"^[A-Za-z]+$\";\r\n");
      out.write("            var patternPassword=\"^[A-Za-z0-9]+$\";\r\n");
      out.write("            if(name.match(patternName)&& password.match(patternPassword))\r\n");
      out.write("            {\r\n");
      out.write("            \treturn true;\r\n");
      out.write("            \t\r\n");
      out.write("        \t   }\r\n");
      out.write("            else if(name.match(patternName)==null && password.match(patternPassword)==null)\r\n");
      out.write("            \t{\r\n");
      out.write("            \tdocument.getElementById(\"error1\").innerHTML=\"Name can be char\";\r\n");
      out.write("            \tdocument.getElementById(\"error2\").innerHTML=\"password can be alphanumeric \";\r\n");
      out.write("            \treturn false;\r\n");
      out.write("            \t\r\n");
      out.write("            \t}\r\n");
      out.write("            else if(name.match(patternName)==null)\r\n");
      out.write("            {\r\n");
      out.write("            \tdocument.getElementById(\"error1\").innerHTML=\"Name can only be char \";\r\n");
      out.write("            \tdocument.getElementById(\"error2\").innerHTML=\"\";\r\n");
      out.write("            \treturn false;\r\n");
      out.write("            }\r\n");
      out.write("            else if(password.match(patternPassword)==null)\r\n");
      out.write("            {\r\n");
      out.write("            \tdocument.getElementById(\"error1\").innerHTML=\"\";\r\n");
      out.write("            \tdocument.getElementById(\"error2\").innerHTML=\"password can be alphanumeric\";\r\n");
      out.write("            \treturn false;\r\n");
      out.write("            }\r\n");
      out.write("\t    }\r\n");
      out.write("   */\r\n");
      out.write("\t/*    function validate(){\r\n");
      out.write("\tvar name=document.getElementById(\"id1\").value;\r\n");
      out.write("\tvar password=document.getElementById(\"id2\").value;\t\r\n");
      out.write("\r\n");
      out.write("\t   if(name.trim().toLowerCase()==\"admin\" && password.trim()==\"admin\")\r\n");
      out.write("\t   {\r\n");
      out.write("\t\t   return true;\r\n");
      out.write("\t   }\r\n");
      out.write("\t   else if(name.trim()==\"\" && password.trim()==\"\")\r\n");
      out.write("\t\t   {\r\n");
      out.write("\t\t   document.getElementById(\"error1\").innerHTML=\"name cannot be\";\r\n");
      out.write("\t\t   document.getElementById(\"error2\").innerHTML=\"password cannot match\";\r\n");
      out.write("\t\t   return false;\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t   else if(name.trim()==\"\")\r\n");
      out.write("       {\r\n");
      out.write("\t\t   document.getElementById(\"error1\").innerHTML=\"name cannot be\";\r\n");
      out.write("\t\t   document.getElementById(\"error2\").innerHTML=\"\";\r\n");
      out.write("       \treturn false;\r\n");
      out.write("       }\r\n");
      out.write("       else if(password.trim()==\"\")\r\n");
      out.write("       {\r\n");
      out.write("    \t   document.getElementById(\"error1\").innerHTML=\"\";\r\n");
      out.write("\t\t   document.getElementById(\"error2\").innerHTML=\"password cannot match\";\r\n");
      out.write("       \treturn false;\r\n");
      out.write("       }\r\n");
      out.write("       else\r\n");
      out.write("    \t   {\r\n");
      out.write("    \t   document.getElementById(\"error1\").innerHTML=\"name cannot be\";\r\n");
      out.write("\t\t   document.getElementById(\"error2\").innerHTML=\"password cannot\";\r\n");
      out.write("\t\t   return false;\r\n");
      out.write("    \t   }\r\n");
      out.write("    \t   }\r\n");
      out.write("   \t  */\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
