/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2019-03-08 07:39:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("Hi ");
      out.print(session.getAttribute("session") );
      out.write('\r');
      out.write('\n');
      out.print(session.getId());
      out.write("\r\n");
      out.write("\t<h1>Registration Form</h1>\r\n");
      out.write("\t<form method=\"get\" action=\"Detaile.jsp\" onsubmit=\"return validate()\">\r\n");
      out.write("\t<script>String username = request.getParameter(\"username\");\r\n");
      out.write("\tSystem.out.println(username);\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\tUser Name :\r\n");
      out.write("\t<input type=\"text\" autofocus name=\"name\" id=\"name\" placeholder=\"Full Name\" /><br /><br />\r\n");
      out.write("\t<span id='nameError'></span>\r\n");
      out.write("\tUser Password:\r\n");
      out.write("\t<input type=\"password\" name=\"password\" placeholder=\"Password\" size=\"10\" ><br /><br />\r\n");
      out.write("\r\n");
      out.write("\tGender:\r\n");
      out.write("\t<input type=\"radio\" name=\"gender\" value=\"Male\" class=\"gender\" checked/>Male\r\n");
      out.write("\t<input type=\"radio\" name=\"gender\" value=\"Female\" class=\"gender\"/>Female\r\n");
      out.write("\t<span id='genderError'></span>\r\n");
      out.write("\t<br /><br />\r\n");
      out.write("\tcities :\r\n");
      out.write("\t<input type=\"checkbox\" name=\"city\" class=\"city\" value=\"Bangalore\"/>Bangalore\r\n");
      out.write("\t<input type=\"checkbox\" name=\"city\" class=\"city\" value=\"Mysore\"/>Mysore\r\n");
      out.write("\t<input type=\"checkbox\" name=\"city\" class=\"city\" value=\"Mumbai\"/>Mumbai\r\n");
      out.write("\t<input type=\"checkbox\" name=\"city\" class=\"city\" value=\"Pune\"/>Pune\r\n");
      out.write("\t<span id='cityError'></span>\r\n");
      out.write("\t<br /><br />\r\n");
      out.write("\tAddress:\r\n");
      out.write("\t<textarea name=\"address\" ></textarea><br /><br />\r\n");
      out.write("\ttechnologies :\r\n");
      out.write("\t<select name=\"technology\">\r\n");
      out.write("\t\t<option value=\"PHP\" selected>PHP</option>\r\n");
      out.write("\t\t<option value=\"HTML\">HTML</option>\r\n");
      out.write("\t\t<option value=\"CSS\">CSS</option>\r\n");
      out.write("\t\t<option value=\"Javascript\">Javascript</option>\r\n");
      out.write("\t</select></br /><br />\r\n");
      out.write("\t<input type=\"submit\" value=\"Submit Form\">\r\n");
      out.write("\t\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<script type=text/javascript>\r\n");
      out.write("\tfunction validate(){\r\n");
      out.write("\t\tvar name=document.getElementById(\"name\").value;\r\n");
      out.write("\t\tvar flagName=nameValidate(name);\r\n");
      out.write("\t\tvar gender=document.getElementsByClassName(\"gender\");\r\n");
      out.write("\t\tvar flagGender=genderValidate(gender);\r\n");
      out.write("\t\tvar gender=document.getElementsByClassName(\"city\");\r\n");
      out.write("\t\tvar flagCity=cityValidate(city);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(flagName && flagGender && flagCity)\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\t//document.getElementById(\"nameError\").innerHtml=\"Name can only char\";\r\n");
      out.write("\t\t//document.getElementById(\"nameError\").style.color=\"red\";\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction nameValidate(name){\r\n");
      out.write("\t\tif(name.match(\"^[A-Za-z]+$\"))\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\tdocument.getElementById(\"nameError\").innerHtml=\"Name can only char\";\r\n");
      out.write("\t\tdocument.getElementById(\"nameError\").style.color=\"red\";\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction genderValidate(gender){\r\n");
      out.write("\t\tvar flag=false;\r\n");
      out.write("\t\tfor(var i=0;i<gender.length;i++){\r\n");
      out.write("\t\t\tif(gender[i].checked){\r\n");
      out.write("\t\t\t\tflag=true;\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t if(!flag){\r\n");
      out.write("\t\t\tdocument.getElementById(\"genderError\").innerHtml=\"choose gender\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"genderError\").style.color=\"red\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn flag;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction cityValidate(city){\r\n");
      out.write("\t\tvar flag=false;\r\n");
      out.write("\t\tfor(var i=0;i<city.length;i++){\r\n");
      out.write("\t\t\tif(city[i].checked){\r\n");
      out.write("\t\t\t\tflag=true;\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\tif(!flag){\r\n");
      out.write("\t\t\tdocument.getElementById(\"cityError\").innerHtml=\"choose city name\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"cityError\").style.color=\"red\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn flag;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tSystem.out.println(ctx.getInitParameter(\"context\"));\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
