/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2019-03-12 06:05:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AddBook_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"87ceeb\">\r\n");
      out.write("\r\n");
      out.write("<center><h2>Library Management System</h2></center>\r\n");
      out.write("<!--Once the form is submitted, all the form data is forwarded to InsertBooks.php -->\r\n");
      out.write("<form onsubmit=\"return validation()\" action=\"AddBooksServlet\">\r\n");
      out.write(" \r\n");
      out.write("<table border=\"2\" align=\"center\" cellpadding=\"5\" cellspacing=\"5\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td> Enter Book Code:</td>\r\n");
      out.write("<td> <input type=\"text\" id=\"bookCode\" name=\"bookCode\" size=\"48\"> </td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td></td><td><span id=\"co\"></span></td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td> Enter BookName :</td>\r\n");
      out.write("<td> <input type=\"text\" id=\"bookName\" name=\"bookName\" size=\"48\"> </td>\r\n");
      out.write("</tr><tr><td></td><td><span id=\"na\"></span></td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td> Enter Author :</td>\r\n");
      out.write("<td> <input type=\"text\" id=\"author\" name=\"author\" size=\"48\"> </td>\r\n");
      out.write("</tr><tr><td></td><td><span id=\"aut\"></span></td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td> Enter Publication: </td>\r\n");
      out.write("<td> <input type=\"text\" id=\"publication\" name=\"publication\" size=\"48\"> </td>\r\n");
      out.write("</tr><tr><td></td><td><span id=\"pub\"></span></td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td> Enter Subject : </td>\r\n");
      out.write("<td> <input type=\"text\" id=\"subject\" name=\"subject\" size=\"48\"> </td>\r\n");
      out.write("</tr><tr><td></td><td><span id=\"sub\"></span></td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td> Enter No of Copies : </td>\r\n");
      out.write("<td> <input type=\"text\" id=\"noOfCopies\" name=\"noOfCopies\" size=\"48\"> </td>\r\n");
      out.write("</tr><tr><td></td><td><span id=\"no\"></span></td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td></td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"submit\" value=\"Add\" >\r\n");
      out.write("<input type=\"reset\" value=\"Reset\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function validation(){\r\n");
      out.write("\tflagBookCode= validateBookCode(document.getElementById(\"bookCode\").value);\r\n");
      out.write("\tflagBookName= validateBookName(document.getElementById(\"bookName\").value);\r\n");
      out.write("\tflagAuthor= validateAuthor(document.getElementById(\"author\").value);\r\n");
      out.write("\tflagPublication= validatePublication(document.getElementById(\"publication\").value);\r\n");
      out.write("\tflagSubject= validateSubject(document.getElementById(\"subject\").value);\r\n");
      out.write("\tflagNoOfCopies= validateNoOfCopies(document.getElementById(\"noOfCopies\").value);\r\n");
      out.write("\t\r\n");
      out.write("\tif(flagBookCode && flagBookName && flagAuthor && flagPublication && flagSubject && flagNoOfCopies){\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validateBookCode(code){\r\n");
      out.write("\tif(code.trim()!=\"\")\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\telse{\r\n");
      out.write("\t\tdocument.getElementById(\"co\").innerHTML=\"Enter the code.\"\r\n");
      out.write("\t\tdocument.getElementById(\"co\").style.color='red';\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function validateBookName(name){\r\n");
      out.write("\tif(name.trim()!=\"\")\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\telse{\r\n");
      out.write("\t\tdocument.getElementById(\"na\").innerHTML=\"Enter the name of book.\"\r\n");
      out.write("\t\tdocument.getElementById(\"na\").style.color='red';\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function validateAuthor(author){\r\n");
      out.write("\tif(author.trim()!=\"\")\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\telse{\r\n");
      out.write("\t\tdocument.getElementById(\"aut\").innerHTML=\"Enter the name of author.\"\r\n");
      out.write("\t\tdocument.getElementById(\"aut\").style.color='red';\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function validatePublication(publication){\r\n");
      out.write("\tif(publication.trim()!=\"\")\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\telse{\r\n");
      out.write("\t\tdocument.getElementById(\"pub\").innerHTML=\"Enter the name of publication.\"\r\n");
      out.write("\t\tdocument.getElementById(\"pub\").style.color='red';\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function validateSubject(subject){\r\n");
      out.write("\tif(subject.trim()!=\"\")\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\telse{\r\n");
      out.write("\t\tdocument.getElementById(\"sub\").innerHTML=\"Enter the subject.\"\r\n");
      out.write("\t\tdocument.getElementById(\"sub\").style.color='red';\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function validateNoOfCopies(noOfCopies){\r\n");
      out.write("\tif(noOfCopies.trim()!=\"\")\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\telse{\r\n");
      out.write("\t\tdocument.getElementById(\"no\").innerHTML=\"Enter the number of copies.\"\r\n");
      out.write("\t\tdocument.getElementById(\"no\").style.color='red';\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
