/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2019-03-12 05:48:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AddEvents_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body background=\"images/1111.jpg\">\r\n");
      out.write("<center><h2>Library Management System</h2></center>\r\n");
      out.write("<!--Once the form is submitted, all the form data is forwarded to InsertBooks.php -->\r\n");
      out.write("\r\n");
      out.write("<form >\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<table bgcolor=\"lightblue\" border=\"2\" align=\"center\" cellpadding=\"5\" cellspacing=\"5\">\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td> Enter Event Name:</td>\r\n");
      out.write("<td> <input type=\"text\" id=\"eventName\" name=\"e_Name\" size=\"48\"> </td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td></td><td><span id=\"ena\"></span></td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td> Enter Event Date :</td>\r\n");
      out.write("<td> <input type=\"text\" id=\"eventDate\" name=\"e_Date\" size=\"48\" placeholder=\"DD/MM/YYYY\"  > </td>\r\n");
      out.write("</tr><tr><td></td><td><span id=\"eda\"></span></td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td> Enter Event Manager :</td>\r\n");
      out.write("<td> <input type=\"text\" id=\"eventMng\" name=\"e_MName\" size=\"48\"> </td>\r\n");
      out.write("</tr><tr><td></td><td><span id=\"mng\"></span></td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td> Enter Contact Number: </td>\r\n");
      out.write("<td> <input type=\"text\" id=\"contactNo\" name=\"ContactNo\" size=\"48\"> </td>\r\n");
      out.write("</tr><tr><td></td><td><span id=\"cnt\"></span></td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td> Enter Email : </td>\r\n");
      out.write("<td> <input type=\"text\" id=\"eMail\" name=\"e_EMail\" size=\"48\" placeholder=\"abc@fgh.aa\" > </td>\r\n");
      out.write("</tr><tr><td></td><td><span id=\"em\"></span></td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td> Enter Venue : </td>\r\n");
      out.write("<td> <input type=\"text\" id=\"eventVenue\" name=\"Venue\" size=\"48\"> </td>\r\n");
      out.write("</tr><tr><td></td><td><span id=\"ve\"></span></td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td></td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"button\" value=\"Add\" onclick= \"validation()\">\r\n");
      out.write("<input type=\"reset\" value=\"Reset\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function validation(){\r\n");
      out.write("\tflagEventName= validateEventName(document.getElementById(\"eventName\").value);\r\n");
      out.write("\tflagEventDate= validateEventDate(document.getElementById(\"eventDate\").value);\r\n");
      out.write("\tflagEventMng= validateEventMng(document.getElementById(\"eventMng\").value);\r\n");
      out.write("\tflagContactNo= validateContactNo(document.getElementById(\"contactNo\").value);\r\n");
      out.write("\tflagEMail= validateEMail(document.getElementById(\"eMail\").value);\r\n");
      out.write("\tflagEventVenue= validateEventVenue(document.getElementById(\"eventVenue\").value);\r\n");
      out.write("\t\r\n");
      out.write("\tif(flagEventName && flagEventDate && flagEventMng && flagContactNo && flagEMail && flagEventVenue){\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validateEventName(eventName){\r\n");
      out.write("\tif(eventName.trim()!=\"\"){\r\n");
      out.write("\t\tnamepattern=\"^[A-Z a-z0-9]+$\";\r\n");
      out.write("\t\tif(eventName.match(namepattern)){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.getElementById(\"ena\").innerHTML=\"Event name can contain only characters and numbers.\"\r\n");
      out.write("\t\t\tdocument.getElementById(\"ena\").style.color='red';\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\telse{\r\n");
      out.write("\t\tdocument.getElementById(\"ena\").innerHTML=\"Enter the event name.\"\r\n");
      out.write("\t\tdocument.getElementById(\"ena\").style.color='red';\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function validateEventDate(eventDate){\r\n");
      out.write("\tif(eventDate.trim()!=\"\"){\r\n");
      out.write("\t\tdatepattern=\"(0?[1-9]|[12][0-9]|3[01])/(0?[1-9]|1[012])/((19|20)\\\\d\\\\d)\";\r\n");
      out.write("\t\tif(eventDate.match(datepattern)){\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.getElementById(\"eda\").innerHTML=\"Event date can contain only  numbers.\"\r\n");
      out.write("\t\t\tdocument.getElementById(\"eda\").style.color='red';\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\telse{\r\n");
      out.write("\t\tdocument.getElementById(\"eda\").innerHTML=\"Enter the event date.\"\r\n");
      out.write("\t\tdocument.getElementById(\"eda\").style.color='red';\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function validateEventMng(eventMng){\r\n");
      out.write("\tif(eventMng.trim()!=\"\"){\r\n");
      out.write("\t\tmngpattern=\"^[A-Z a-z]+$\";\r\n");
      out.write("\t\tif(eventMng.match(mngpattern)){\r\n");
      out.write("\t\t\treturn true;\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\tdocument.getElementById(\"mng\").innerHTML=\"Event manager can contain only  character.\"\r\n");
      out.write("\t\t\tdocument.getElementById(\"mng\").style.color='red';\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\telse{\r\n");
      out.write("\t\tdocument.getElementById(\"mng\").innerHTML=\"Enter the event manager name.\"\r\n");
      out.write("\t\tdocument.getElementById(\"mng\").style.color='red';\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function validateContactNo(contactNo){\r\n");
      out.write("\tif(contactNo.trim()!=\"\"){\r\n");
      out.write("\tnopattern=\"^[0-9]{10}$\";\r\n");
      out.write("\t\tif(contactNo.match(nopattern)){\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\t\tdocument.getElementById(\"cnt\").innerHTML=\"user should provided 10 digits.\"\r\n");
      out.write("\t\t\tdocument.getElementById(\"cnt\").style.color='red';\r\n");
      out.write("\t\treturn false;\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\telse{\r\n");
      out.write("\t\tdocument.getElementById(\"cnt\").innerHTML=\"Enter the contact number.\"\r\n");
      out.write("\t\tdocument.getElementById(\"cnt\").style.color='red';\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function validateEMail(eMail){\r\n");
      out.write("\tif(eMail.trim()!=\"\"){\r\n");
      out.write("\t\temailpattern=\"[a-z0-9]+[@]{1}[a-z]+[.]{1}[a-z]+\";\r\n");
      out.write("\t\tif(eMail.match(emailpattern)){\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\t\tdocument.getElementById(\"em\").innerHTML=\"EMail can contain only  number,character,@.\"\r\n");
      out.write("\t\t\tdocument.getElementById(\"em\").style.color='red';\r\n");
      out.write("\t\treturn false;\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\telse{\r\n");
      out.write("\t\tdocument.getElementById(\"em\").innerHTML=\"Enter the e-mail ID.\"\r\n");
      out.write("\t\tdocument.getElementById(\"em\").style.color='red';\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function validateEventVenue(eventVenue){\r\n");
      out.write("\tif(eventVenue.trim()!=\"\")\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\telse{\r\n");
      out.write("\t\tdocument.getElementById(\"ve\").innerHTML=\"Enter the event venue.\"\r\n");
      out.write("\t\tdocument.getElementById(\"ve\").style.color='red';\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
