/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2019-03-05 11:32:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class NewFile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write(" <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\" name=\"viewport\">\r\n");
      out.write("  <link rel=\"profile\" href=\"http://gmpg.org/xfn/11\">\r\n");
      out.write("  <link rel=\"pingback\" href=\"https://www.library-management.com/xmlrpc.php\">\r\n");
      out.write("  <link href=\"https://www.library-management.com/wp-content/themes/library/fonts/fonts.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"https://www.library-management.com/wp-content/themes/library/css/ionicons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <title>Forgot LMS</title>\r\n");
      out.write("    <link rel='dns-prefetch' href='//s.w.org' />\r\n");
      out.write("<link rel='stylesheet' id='font_awesome-css'  href='https://www.library-management.com/wp-content/themes/library/css/font-awesome.min.css?ver=4.9.8' type='text/css' media='all' />\r\n");
      out.write("<link rel='stylesheet' id='bootstrap-css'  href='https://www.library-management.com/wp-content/themes/library/css/bootstrap.min.css?ver=4.9.8' type='text/css' media='all' />\r\n");
      out.write("<link rel='stylesheet' id='slick-css'  href='https://www.library-management.com/wp-content/themes/library/css/slick.css?ver=4.9.8' type='text/css' media='all' />\r\n");
      out.write("<link rel='stylesheet' id='slick_theme-css'  href='https://www.library-management.com/wp-content/themes/library/css/slick-theme.css?ver=4.9.8' type='text/css' media='all' />\r\n");
      out.write("<link rel='stylesheet' id='button-css'  href='https://www.library-management.com/wp-content/themes/library/css/button.css?ver=4.9.8' type='text/css' media='all' />\r\n");
      out.write("<link rel='stylesheet' id='adminLTE-css'  href='https://www.library-management.com/wp-content/themes/library/css/AdminLTE.min.css?ver=4.9.8' type='text/css' media='all' />\r\n");
      out.write("<link rel='stylesheet' id='iziToastCss-css'  href='https://www.library-management.com/wp-content/themes/library/css/iziToast.min.css?ver=4.9.8' type='text/css' media='all' />\r\n");
      out.write("<link rel='stylesheet' id='tooltipcss-css'  href='https://www.library-management.com/wp-content/themes/library/css/angular-tooltips.css?ver=4.9.8' type='text/css' media='all' />\r\n");
      out.write("<link rel='stylesheet' id='datetimepickerCss-css'  href='https://www.library-management.com/wp-content/themes/library/css/jquery.datetimepicker.min.css?ver=4.9.8' type='text/css' media='all' />\r\n");
      out.write("<link rel='stylesheet' id='angular_bootstrap_toggle_css-css'  href='https://www.library-management.com/wp-content/themes/library/css/angular-bootstrap-toggle.min.css?ver=4.9.8' type='text/css' media='all' />\r\n");
      out.write("<link rel='stylesheet' id='datatable_css-css'  href='https://www.library-management.com/wp-content/themes/library/css/dataTables.bootstrap.min.css?ver=4.9.8' type='text/css' media='all' />\r\n");
      out.write("<link rel='stylesheet' id='mainstyle-css'  href='https://www.library-management.com/wp-content/themes/library/style.css?ver=4.9.8' type='text/css' media='all' />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body  class=\"page-template page-template-forgotpassword page-template-forgotpassword-php page page-id-9 hold-transition skin-blue sidebar-mini\" >\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrapper\" id=\"style-5\">\r\n");
      out.write("\r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("    .skin-blue .wrapper, .skin-blue .main-sidebar, .skin-blue .left-side {\r\n");
      out.write("      background-color: #fff;\r\n");
      out.write("      }\r\n");
      out.write("    \r\n");
      out.write("    .loginmodal-container{\r\n");
      out.write("   background-color: lightblue;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("  </style></div>\r\n");
      out.write("  <div class=\"loginmodal-container\" ng-controller=\"forgotPasswordCtrl\">\r\n");
      out.write("\r\n");
      out.write("    <h1>Library Management</h1><br>\r\n");
      out.write("    <div>\r\n");
      out.write("      <span style=\"font-size: 17px;font-weight: bold;\">Change Password</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <hr style=\"border-top: 2px solid #eee;\"/>\r\n");
      out.write("\r\n");
      out.write("    <form id=\"frmForgotPassword\" onsubmit=\"return validate()\" action=\"ChangePasswordServlet\">\r\n");
      out.write("\r\n");
      out.write("      <p class=\"login-username\">\r\n");
      out.write("        <label for=\"user_login\">Username or Email Address</label>\r\n");
      out.write("        <input type=\"text\" name=\"username\" id=\"user_email\" class=\"form-control fix_radius\" value=\"\" size=\"20\" placeholder=\"Enter Name\"\r\n");
      out.write("               ng-model=\"user_email\">\r\n");
      out.write("        <span id=\"na\"></span>\r\n");
      out.write("      </p>\r\n");
      out.write("\r\n");
      out.write("\t\t<p class=\"New-password\">\r\n");
      out.write("\t\t\t\t<label for=\"user_pass\">New Password</label>\r\n");
      out.write("\t\t\t\t<input type=\"password\" name=\"password\" id=\"password\" class=\"input\" value=\"\" size=\"20\" placeholder=\"Enter New Password\"/>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<span id=\"pw\"></span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<p class=\"Con-password\">\r\n");
      out.write("\t\t\t\t<label for=\"user_pass\">Confirm Password</label>\r\n");
      out.write("\t\t\t\t<input type=\"password\" name=\"confirmpassword\" id=\"confirmpassword\" class=\"input\" onchange=\"passwordConfirmation()\"  value=\"\" size=\"20\" placeholder=\"Confirm Password\"/>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<span id=\"cpw\"></span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("      <p class=\"login-submit\">\r\n");
      out.write("        <input type=\"submit\" value=\"Reset Password\" \r\n");
      out.write("                class=\"btn btn-primary form-control fix_radius pmd-ripple-effect\" />\r\n");
      out.write("      </p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function passwordConfirmation(){\r\n");
      out.write("\t\r\n");
      out.write("\tif(document.getElementById(\"password\").value!=document.getElementById(\"confirmpassword\").value){\r\n");
      out.write("\t\tdocument.getElementById(\"cpw\").innerHTML=\"Password does not match\";\r\n");
      out.write("\t\tdocument.getElementById(\"cpw\").style.color='red';\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validate(){\r\n");
      out.write("\tvar flagName=validateName(document.getElementById(\"user_email\").value);\r\n");
      out.write("\tvar flagPassword=validatePassword(document.getElementById(\"password\").value);\r\n");
      out.write("\tconsole.log(flagName && flagPassword);\r\n");
      out.write("\tif(flagName && flagPassword){\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\t\r\n");
      out.write("\telse{\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validateName(name){\r\n");
      out.write("\tif(name.trim()!=\"\")\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\telse{\r\n");
      out.write("\t\tdocument.getElementById(\"na\").innerHTML=\"Enter your username.\"\r\n");
      out.write("\t\tdocument.getElementById(\"na\").style.color='red';\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validatePassword(password){\r\n");
      out.write("\tif(password!=\"\")\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\telse{\r\n");
      out.write("\t\tdocument.getElementById(\"pw\").innerHTML=\"Enter password.\"\r\n");
      out.write("\t\tdocument.getElementById(\"pw\").style.color='red';\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
