/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2019-03-11 17:56:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.beans.*;

public final class StudentList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Admin</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"page\">\r\n");
      out.write("    <div class=\"headerpart\">\r\n");
      out.write("\t<img src=\"images/header.jpg\" alt=\"oops\" height=\"180px\" width=\"1330px\"></div>\r\n");
      out.write("    <div class=\"linkspart\">\r\n");
      out.write("   \r\n");
      out.write("    <a href = \"DigitalLib.jsp\"><b>DigitalLibrary</b></a> &nbsp;\r\n");
      out.write("\t\r\n");
      out.write("   \r\n");
      out.write("     <div class=\"dropdown\">\r\n");
      out.write("             \r\n");
      out.write("\t<a href = \"BookList.jsp\"><b>Books</b></a>\r\n");
      out.write("\r\n");
      out.write("  \t<div class=\"dropdown-content\">\r\n");
      out.write("   \t \t<a href=\"DisplayBooksServlet\">DisplayBooks</a>\r\n");
      out.write("    \t<a href=\"AddBook.jsp\">AddBooks</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("    <a href = \"BookIssue.jsp\"><b>Issued Books</b></a> &nbsp;\r\n");
      out.write("\t\r\n");
      out.write("    <a href = \"DisplayReservedBooks\"><b>Reserved Books</b></a> &nbsp;\r\n");
      out.write("    \r\n");
      out.write("    <a href = \"home.html\"><b>ViewReports</b></a> &nbsp;\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"dropdown\">\r\n");
      out.write("             \r\n");
      out.write("\t\t<a href = \"home.html\"><b>GenerateReports</b></a>\r\n");
      out.write("\r\n");
      out.write("  \t\t<div class=\"dropdown-content\">\r\n");
      out.write("   \t\t\t <a href=\"StudentListServlet\">StudentList</a>\r\n");
      out.write("    \t\t<a href=\"FacultyListServlet\">FacultyList</a>\r\n");
      out.write("  \t\t\t  <a href=\"#\">BookList</a>\r\n");
      out.write(" \t\t    <a href=\"AddEvents.jsp\">EventList</a>\r\n");
      out.write(" \t\t </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<a href = \"LogoutServlet\"><b>LOGOUT</b></a> &nbsp;\r\n");
      out.write("  \r\n");
      out.write("    </div>\r\n");
      out.write("  <div class=\"bodypart\">\r\n");
      out.write("<form align=\"center\">\r\n");
      out.write("<table border=1 >\r\n");
      out.write("<tr>\r\n");
      out.write("<th>User Name</th><th>Password</th><th>Lib Id</th><th>Reg No.</th><th>Branch</th><th>Section</th><th>Semester</th><th>Year of Admission</th>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");

	ArrayList<StudentsInfo> al=(ArrayList)request.getAttribute("students");

	Iterator<StudentsInfo> it=al.iterator();
	while(it.hasNext()){		
		StudentsInfo d= (StudentsInfo)it.next();

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>");
      out.print(d.getUsername() );
      out.write("</td>\r\n");
      out.write("\t\t<td>");
      out.print(d.getPassword() );
      out.write("</td>\r\n");
      out.write("\t\t<td>");
      out.print(d.getLibId() );
      out.write("</td>\r\n");
      out.write("\t\t<td>");
      out.print(d.getRegNo() );
      out.write("</td>\r\n");
      out.write("\t\t<td>");
      out.print(d.getBranch() );
      out.write("</td>\r\n");
      out.write("\t\t<td>");
      out.print(d.getSection() );
      out.write("</td>\r\n");
      out.write("\t\t<td>");
      out.print(d.getSemester() );
      out.write("</td>\r\n");
      out.write("\t\t<td>");
      out.print(d.getYearOfAdm() );
      out.write("</td>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
 	}	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("<br><br><br><br><br><br><br><br><br><br><br><br>\r\n");
      out.write("<div class = \"footerpart\">\r\n");
      out.write("<center>\r\n");
      out.write("<img src=\"images/facebookicon.png\" alt=\"facebook logo\" width=\"20\" height=\"20\">&nbsp;\r\n");
      out.write("    <img src=\"images/twittericon.png\" alt=\"twitter logo\" width=\"20\" height=\"20\">&nbsp;\r\n");
      out.write("    <img src=\"images/linkedinicon.png\" alt=\"linkedin logo\" width=\"20\" height=\"20\">\r\n");
      out.write("\t <br />\r\n");
      out.write("2019.All Copyrights Reserved\r\n");
      out.write("</center>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
